update_url: 'https://github.com/XxGoldenbluexX/Vi6Clean/raw/master/build/Vi6Clean.jar'

majordom:
   delay: 40 # Delai en tick
   
koth:
   limit: 2
   
preparation:
   duration: 4800 #durée de la phase de préparation en ticks