update_url: 'https://github.com/XxGoldenbluexX/Vi6Clean/raw/master/build/Vi6Clean.jar'

majordom.delay: 40 # Delai en tick
   
koth.limit: 2
   
preparation.duration: 4800 #durée de la phase de préparation en ticks

game_end_spectator_time: 5 # délais en secondes

invisibility:
   step_distance: 0.5
   particle_count: 3
  
asthma:
   half_drumstick_consumption_delay : 1.0 
   half_drumsitck_moving_regeneration_delay: 2.0
   idle_regeneration_multiplier: 2
   delay_before_considering_idle: 0.25
   max_half_drumstick_after_capture: 10

infiltration:
   delay_between_capture: 30.0 #délai entre 2 captures d'artéfacts en secondes
   delay_before_escape: 30.0 #délai avant de pouvoir s'enfuir en secondes
   
