update_url: 'https://github.com/XxGoldenbluexX/Vi6Clean/raw/master/build/Vi6Clean.jar'

majordom:
   delay: 40 # Delai en tick

tool:
   double_jump:
      display_name: Double saut
      price: 300
      amount_limit: 1
      shop_icon: GOLDEN_BOOTS
      lore:
         - <lore>permet de sauter une fois
         - <lore> en l'air, en appuyant
         - <lore>deux fois sur <important><key:key.jump></important>
      power: 0.5 # vitesse en block/s
   parabolic_mic:
      range: 20.0 # distance en block
   bush:
      fadeoff: 30 # delai en tick
      reveal_range: 2.0 # distance en block