name: Vi6Clean
version: 1.0
api-version: '1.21.11'
author: XxGoldenbluexX
load: POSTWORLD
bootstrapper: fr.nekotine.vi6clean.Vi6Bootstrapper
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
    voicechat:
      load: BEFORE
      required: true
      join-classpath: true