name: Vi6Clean
version: 1.0
main: fr.nekotine.vi6clean.Vi6Main
api-version: '1.21.7'
author: XxGoldenbluexX
load: POSTWORLD
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
    voicechat:
      load: BEFORE
      required: true
      join-classpath: true