name: Build ressource packs zips

on:
  push:
    branches:
      - main
    paths:
      - 'ResourcePack/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ResourcePack/**'
  workflow_dispatch:
    branches:
      - main

jobs:
  list-resourcepacks:
    runs-on: ubuntu-slim
    outputs:
      packnames: ${{ steps.list.outputs.folders }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: List pack folders
      id: list
      run: |
        folders=$(find ResourcePack -mindepth 1 -maxdepth 1 -type d -printf '"%f",' | sed 's/,$//')
        echo "folders=[$folders]"
        echo "folders=[$folders]" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-slim
    needs: list-resourcepacks
    strategy:
      matrix:
        packname: ${{ fromJSON(needs.list-resourcepacks.outputs.packnames) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: zip files
      uses: vimtor/action-zip@v1.3
      with:
        files: "ResourcePack/${{ matrix.packname }}/"
        dest: "${{ matrix.packname }}.zip"
    - name: generate sha1 files
      run: |
        sha=$(sha1sum "${{ matrix.packname }}.zip" | awk '{print $1}')
        echo "$sha" > "${{ matrix.packname }}.zip.sha1"
        echo "sha1 is $(cat "${{ matrix.packname }}.zip.sha1") for ${{ matrix.packname }}.zip"
    - name: upload resourcepack zip artifact
      uses: actions/upload-artifact@v7
      with:
        name: "resourcepack-${{ matrix.packname }}"
        path: "${{ matrix.packname }}.zip"
        archive: false
    - name: upload sha1 artifact
      uses: actions/upload-artifact@v7
      with:
        name: "resourcepack-sha1-${{ matrix.packname }}"
        path: "${{ matrix.packname }}.zip.sha1"
        archive: false
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v8
      with:
        path: artifactsfolder
    - name: Bump version and push tag
      id: tagbump
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        TAG_PREFIX: v
        DEFAULT_BUMP: patch
    - name: Create resourcepack release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ steps.tagbump.outputs.new_tag }}
        files: artifactsfolder/*